# Generated by Django 4.0 on 2022-04-24 09:17

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('file', models.FileField(blank=True, null=True, upload_to='information/%Y%m%d', verbose_name='通知文件')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_author', to='auth.user', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '学院通知',
                'verbose_name_plural': '学院通知',
            },
        ),
    ]
