# Generated by Django 4.0 on 2022-02-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('salary', models.IntegerField()),
                ('photo', models.ImageField(upload_to='teachers')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
