# Generated by Django 4.0 on 2022-04-27 11:53

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('job_title', models.CharField(choices=[(0, '特聘教授'), (1, '教授'), (2, '副教授'), (3, '讲师'), (4, '助教'), (5, '副研究员')], max_length=50, verbose_name='职称')),
                ('degree', models.CharField(choices=[(0, '博士'), (1, '硕士'), (2, '学士'), (3, '其他')], max_length=50, verbose_name='学位')),
                ('personal_profile', mdeditor.fields.MDTextField(verbose_name='个人简介')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='教师图片')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
