# Generated by Django 4.0 on 2022-02-20 07:53

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师信息管理', 'verbose_name_plural': '教师列表'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(max_length=50, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='teachers', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
