# Generated by Django 4.0 on 2022-02-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teachers', '0002_alter_teacher_options_alter_teacher_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='auth.user', verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers', verbose_name='头像'),
        ),
    ]
