# Generated by Django 4.0 on 2022-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(blank=True, choices=[(0, '特聘教授'), (1, '教授'), (2, '副教授'), (3, '讲师'), (4, '助教'), (5, '副研究员')], max_length=50, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
