# Generated by Django 4.0 on 2022-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_job_title_alter_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, choices=[(0, '博士'), (1, '硕士'), (2, '学士'), (3, '其他')], max_length=50, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(blank=True, choices=[(0, '特聘教授'), (1, '教授'), (2, '副教授'), (3, '讲师'), (4, '助教'), (5, '副研究员'), (6, '其他')], max_length=50, verbose_name='职称'),
        ),
    ]
