# Generated by Django 4.0 on 2022-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_degree_alter_teacher_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=50, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(blank=True, choices=[('0', '特聘教授'), ('1', '教授'), ('2', '副教授'), ('3', '讲师'), ('4', '助教'), ('6', '其他')], max_length=50, verbose_name='职称'),
        ),
    ]
