# Generated by Django 4.0 on 2022-04-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacher_position_alter_teacher_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, choices=[('博士', '博士'), ('硕士', '硕士'), ('学士', '学士'), ('其他', '其他')], max_length=20, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(blank=True, choices=[('特聘教授', '特聘教授'), ('教授', '教授'), ('副教授', '副教授'), ('讲师', '讲师'), ('助教', '助教'), ('其他', '其他')], max_length=50, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, choices=[('院长', '院长'), ('副院长', '副院长'), ('研究员', '研究员'), ('副研究员', '副研究员'), ('助理研究员', '助理研究员'), ('其他', '其他')], max_length=50, verbose_name='职务'),
        ),
    ]
