# Generated by Django 4.0 on 2022-04-28 08:46

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_teacher_degree_alter_teacher_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMorality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '师德师风建设',
                'verbose_name_plural': '师德师风建设',
            },
        ),
    ]
