# Generated by Django 4.0 on 2022-04-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_teachermorality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermorality',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
