# Generated by Django 4.0 on 2022-04-28 11:20

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teachermorality_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
            },
        ),
    ]
