# Generated by Django 4.0 on 2022-04-28 11:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_recruiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiting',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='招聘信息'),
        ),
    ]
