# Generated by Django 4.0 on 2022-05-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_partyfileandtrends_alter_partybuilding_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partybuilding',
            old_name='time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='partyfileandtrends',
            old_name='time',
            new_name='create_time',
        ),
    ]
