# Generated by Django 4.0 on 2022-05-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msboard',
            name='reply_to',
        ),
        migrations.CreateModel(
            name='MSboardReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('msboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSboard.msboard', verbose_name='关联主表')),
            ],
        ),
    ]
