# Generated by Django 4.0 on 2022-05-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSboard', '0002_remove_msboard_reply_to_msboardreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MSboardReply',
        ),
    ]
