# Generated by Django 4.0 on 2022-05-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSboard', '0003_delete_msboardreply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MSboard',
            new_name='board',
        ),
    ]
