# Generated by Django 4.0 on 2022-04-29 13:13

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成果名称')),
                ('description', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='简介')),
                ('file', models.FileField(blank=True, null=True, upload_to='research/achievements/', verbose_name='文件')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科研成果',
                'verbose_name_plural': '科研成果',
            },
        ),
        migrations.CreateModel(
            name='institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机构名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='research/institutions/', verbose_name='机构logo')),
                ('description', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='简介')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科研机构',
                'verbose_name_plural': '科研机构',
            },
        ),
        migrations.AlterField(
            model_name='research',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='research',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='research/files/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
