# Generated by Django 4.0 on 2022-04-30 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_achievements_institutions_alter_research_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': '科研动态', 'verbose_name_plural': '科研动态'},
        ),
    ]
