# Generated by Django 4.0 on 2022-05-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_research_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='institutions',
            old_name='date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='research',
            old_name='date',
            new_name='create_time',
        ),
    ]
