# Generated by Django 4.0 on 2022-05-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_rename_name_achievements_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='file',
        ),
    ]
