# Generated by Django 4.0 on 2022-04-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant', models.ImageField(upload_to='cover/%Y%m%d')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_cover', to='News.cover', verbose_name='封面'),
        ),
    ]
