# Generated by Django 4.0 on 2022-01-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='files',
            field=models.FileField(default=None, upload_to='app/static', verbose_name='文件'),
        ),
    ]
