# Generated by Django 4.0 on 2022-04-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_cover_news_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='文章内容'),
        ),
    ]
