# Generated by Django 4.0 on 2022-01-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_avatar_news_delete_infos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='time',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='news',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
