# Generated by Django 4.0 on 2022-01-24 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_time_news_create_time_news_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='news',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='上次更新时间'),
        ),
    ]
