# Generated by Django 4.0 on 2022-05-12 09:20

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_alter_news_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body_file',
            field=models.FileField(blank=True, null=True, upload_to='body/%Y%m%d', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='文章内容'),
        ),
    ]
