# Generated by Django 4.0 on 2022-01-24 08:25

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_create_time_alter_news_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '学院新闻', 'verbose_name_plural': '新闻列表'},
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
    ]
