# Generated by Django 4.0 on 2022-05-12 09:52

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_news_body_file_alter_news_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='body_file',
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
    ]
