# Generated by Django 4.0 on 2022-01-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0009_alter_news_author_alter_news_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='auth.user', verbose_name='发布者'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
