# Generated by Django 4.0 on 2022-02-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0010_remove_news_avatar_alter_news_author_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_author', to='auth.user', verbose_name='发布者'),
        ),
    ]
