# Generated by Django 4.0 on 2022-01-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_avatar_infos_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info', to='info.avatar'),
        ),
    ]
