# Generated by Django 4.0 on 2022-01-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_infos_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos',
            name='avatar',
        ),
        migrations.AddField(
            model_name='infos',
            name='files',
            field=models.FileField(default=None, upload_to='app/static', verbose_name='文件'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
