# Generated by Django 4.0 on 2022-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_infos_avatar_infos_files_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='files',
            field=models.FileField(default=None, upload_to='info/files', verbose_name='文件'),
        ),
    ]
