# Generated by Django 4.0 on 2022-02-09 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('info', '0007_info_delete_infos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('body', mdeditor.fields.MDTextField(verbose_name='通知内容')),
                ('files', models.FileField(default=None, upload_to='info/files', verbose_name='文件')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='上次更新时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_author', to='auth.user', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '学院通知',
                'verbose_name_plural': '通知列表',
            },
        ),
    ]
