# Generated by Django 4.0 on 2022-04-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='GroupNews',
        ),
    ]
