# Generated by Django 4.0 on 2022-05-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_rename_news_groupnews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='System',
            new_name='Manage',
        ),
    ]
