# Generated by Django 4.0 on 2022-05-06 11:00

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0003_rename_system_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('desc', mdeditor.fields.MDTextField(max_length=255, verbose_name='文章内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '管理制度',
                'verbose_name_plural': '管理制度',
            },
        ),
        migrations.DeleteModel(
            name='Manage',
        ),
    ]
