# Generated by Django 4.0 on 2022-05-12 08:18

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_management_delete_manage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='desc',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='groupnews',
            name='desc',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='desc',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='management',
            name='desc',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='party',
            name='desc',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
    ]
