# Generated by Django 4.0 on 2022-05-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0005_alter_group_desc_alter_groupnews_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honor',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='honor/%Y/%m', verbose_name='文件'),
        ),
    ]
