# Generated by Django 4.0 on 2022-05-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0007_honor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honor',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='honor', verbose_name='封面图片'),
        ),
    ]
