# Generated by Django 4.0 on 2022-04-29 02:58

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('本科生', '本科生'), ('研究生', '研究生'), ('博士生', '博士生')], max_length=20)),
                ('description', mdeditor.fields.MDTextField(blank=True, max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '专业介绍',
                'verbose_name_plural': '专业介绍',
            },
        ),
    ]
