# Generated by Django 4.0 on 2022-04-29 03:04

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='category',
            field=models.CharField(choices=[('本科生', '本科生'), ('研究生', '研究生'), ('博士生', '博士生')], max_length=20, verbose_name='学生类别'),
        ),
        migrations.AlterField(
            model_name='major',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='major',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, max_length=200, verbose_name='专业介绍'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='专业名称'),
        ),
    ]
