# Generated by Django 4.0 on 2022-04-29 06:13

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_major_category_alter_major_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='培养方案名称')),
                ('category', models.CharField(choices=[('本科生', '本科生'), ('研究生', '研究生'), ('博士生', '博士生')], max_length=20, verbose_name='学生类别')),
                ('file', models.FileField(blank=True, upload_to='student/plan/', verbose_name='培养方案文件')),
                ('description', mdeditor.fields.MDTextField(blank=True, max_length=200, verbose_name='培养方案介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '培养方案',
                'verbose_name_plural': '培养方案',
            },
        ),
    ]
