# Generated by Django 4.0 on 2022-04-29 12:32

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_recruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='标题')),
                ('category', models.CharField(choices=[('本科生', '本科生'), ('研究生', '研究生'), ('博士生', '博士生')], default='研究生', max_length=20, verbose_name='学生类别')),
                ('file', models.FileField(blank=True, upload_to='student/Enrollment/', verbose_name='文件')),
                ('description', mdeditor.fields.MDTextField(blank=True, max_length=200, verbose_name='文字介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学院招生',
                'verbose_name_plural': '学院招生',
            },
        ),
        migrations.DeleteModel(
            name='Recruit',
        ),
    ]
