# Generated by Django 4.0 on 2022-04-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_employment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='标题')),
                ('category', models.CharField(choices=[('学习资料', '学习资料'), ('软件', '软件')], max_length=20, verbose_name='学生类别')),
                ('file', models.FileField(blank=True, upload_to='student/learning/', verbose_name='文件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习资料&软件',
                'verbose_name_plural': '学习资料&软件',
            },
        ),
    ]
