# Generated by Django 4.0 on 2022-04-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_learning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='teaching',
            old_name='name',
            new_name='title',
        ),
    ]
