# Generated by Django 4.0 on 2022-05-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_name_course_title_rename_name_major_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='category',
            field=models.CharField(choices=[('本科生', '本科生'), ('研究生', '研究生'), ('博士生', '博士生')], max_length=20, verbose_name='学生类别'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='category',
            field=models.CharField(choices=[('本科生', '本科生'), ('研究生', '研究生'), ('博士生', '博士生')], max_length=20, verbose_name='学生类别'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='category',
            field=models.CharField(choices=[('学习资料', '学习资料'), ('软件', '软件')], max_length=20, verbose_name='文件类别'),
        ),
    ]
