# Generated by Django 4.0 on 2022-05-09 11:18

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_employment_category_alter_enrollment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='精品课程介绍'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='文字介绍'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='文字介绍'),
        ),
        migrations.AlterField(
            model_name='major',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='专业介绍'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='文字介绍'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='培养方案介绍'),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='教学成果介绍'),
        ),
    ]
